export const keyboards = [
  {
    id: "atk-edge60he",
    title: "ATK EDGE60 HE ULTIMATE",
    short:
      "ATK EDGE 60HE ULTIMATE Esports Magnetic Keyboard - LEVIATAN Collaboration",
    price: 229,
    layout: "60",
    available: true,
    isNew: false,
    lowStock: false,
    images: [
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/edge60/2_27ffe2b5-f717-4c2f-940c-959572442aa1.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/edge60/1_f9f267de-73a2-46f0-b918-9d35850c4593.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/edge60/ATK_EDGE_60_HE_Keyboard.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/edge60/edge60-translucent-keycap-closeup.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/edge60/edge60-with-partial-transparent-keycaps.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/edge60/edge60-with-transparent-keycaps.jpg",
    ],
    category: "keyboards",
    sellerRating: 10,
    specs: {
      layout: "60% (61 keys)",
      case: "Full Aluminum CNC case",
      keycaps: "PBT dye‑sublimation keycaps",
      switches: "Hot‑swap / magnetic switches",
      pollingRate: "8K Hz",
      latency: "0.08ms",
      singleKeyScanRate: "256K",
      precision: "0.001mm",
      fullKeyScanRate: "32K N-Key",
      features: [
        "Super stable RT",
        "2 Profile RT Button",
        "Functions SOCD / DKS / RT / MT / TGL / Key remapping",
        "Champion Preset",
        "Cherry Profile Keycaps",
      ],
    },
    options: [
      {
        name: "LEVIANTAN Edition",
        available: true,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/edge60/leviatan.jpg",
      },
      {
        name: "WOLVES Edition",
        available: false,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/edge60/wolves.jpg",
      },
    ],
  },
  {
    id: "titan68",
    title: "TITAN68 HE (TITAN NATION)",
    short:
      "TITAN68 HE Peak Performance Esports Magnetic Keyboard - TRUE 8000Hz Polling Rate",
    price: 90,
    layout: "65",
    available: true,
    isNew: false,
    lowStock: false,
    sellerRating: 8.5,
    images: [
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/titan68/1.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/titan68/2.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/titan68/3.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/titan68/4.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/titan68/5.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/titan68/6.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/titan68/7.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/titan68/8.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/titan68/9.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/titan68/10.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/titan68/11.jpg",
    ],
    category: "keyboards",
    specs: {
      layout: "65% (68 keys)",
      case: "High-End CNC Aluminum Craftsmanship",
      switches: "Gateron Magnetic Jade",
      pollingRate: "8K Hz",
      latency: "0.125ms",
      fullKeyScanRate: "32K",
      rtRange: "0.001 ~ 3.4mm",
      features: [
        "Multifunction Physical Button (Short press for RGB, long press for RT mode)",
        "Adjustable Rapid-Trigger Stabilizer Algorithm",
        "Functions: SOCD / DKS / RT / MT / TGL / Key remapping / Music Rhythm / Emergency Stop",
        "PCB Nano Waterproof Technology",
        "Aluminum Alloy Position Plate",
        "Standard PBT / Five-sided Dye-Sub keycaps (PRO)",
      ],
    },
    options: [
      {
        name: "TITAN68HE PURPLE THEME",
        available: true,
        price: 90,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/titan68/purple.png",
      },
      {
        name: "TITAN68HE RED THEME",
        available: true,
        price: 110,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/titan68/red.png",
      },
    ],
  },
  {
    id: "atk-68rx",
    title: "ATK 68 RX",
    short:
      "ATK 68 RX - Meet the Forged Carbon Limited Edition, paired with Cosmic switches. Designed for a unique feel.",
    price: 70,
    layout: "65",
    available: false,
    isNew: false,
    lowStock: false,
    images: [
      "https://halleffectkeyboard.com/wp-content/uploads/2025/08/1-12.jpg",
      "https://www.atk.store/cdn/shop/files/68RX_-_PC__02.jpg?v=1764137347&width=2000",
      "https://www.atk.store/cdn/shop/files/68RX_-_PC__07.jpg?v=1764137333&width=2000",
      "https://www.atk.store/cdn/shop/files/68RX_-_PC__10.jpg?v=1764137293&width=2000",
      "https://www.atk.store/cdn/shop/files/68RX_-_PC__04.jpg?v=1764137293&width=2000",
      "https://www.atk.store/cdn/shop/files/68RX_-_PC__06.jpg?v=1764137256&width=2000",
      "https://www.atk.store/cdn/shop/files/68RX_-_PC__05.jpg?v=1764137259&width=2000",
      "https://www.atk.store/cdn/shop/files/68RX_-_PC__03.jpg?v=1764137253&width=2000",
      "https://www.atk.store/cdn/shop/files/68RX_-_PC__08.jpg?v=1764137258&width=2000",
    ],
    category: "keyboards",
    specs: {
      layout: "65% (68 keys)",
      case: "Aluminum Alloy Position Plate",
      pollingRate: "8K Hz",
      latency: "0.08ms",
      singleKeyScanRate: "256K",
      fullKeyScanRate: "32K",
      precision: "0.005mm",
      features: [
        "Zero Dead-Zone",
        "Preset Switch Physical Button (up to 3 profiles)",
        "Super stable RT",
        "Detachable CNC Aluminum Wrist Rest",
        "6-Layers Flagship Padding",
        "Adjustable Dual Stage Feet",
        "Cherry Profile Keycaps, Frosted PC",
      ],
    },
    options: [
      {
        name: "White / Wolf Switches",
        available: false,
        image:
          "https://www.atk.store/cdn/shop/files/0a880f505c69d7e7d07d0e5117ab8804.jpg?v=1753930212",
      },
      {
        name: "Pink / Wolf Switches",
        available: false,
        image:
          "https://www.atk.store/cdn/shop/files/a41da8b0ebf45d9eef904598ea8249c9.jpg?v=1753930438",
      },
      {
        name: "Black / Wolf Switches",
        available: false,
        image:
          "https://www.atk.store/cdn/shop/files/ac32e9e1554198b2e59119946fb32d1c.jpg?v=1753930438",
      },
      {
        name: "Black - Forged Carbon Limited / Wolf Switches",
        available: false,
        image:
          "https://www.atk.store/cdn/shop/files/20251126-142222.jpg?v=1764138160",
      },
    ],
  },
  {
    id: "made68pro",
    title: "MEELGEEK MADE68 PRO",
    short:
      "The MADE68 Pro goes beyond a simple keyboard. It's a truly modular experience, engineered with wireless freedom and MelGeek HIVE",
    price: 140,
    layout: "68",
    available: false,
    isNew: false,
    lowStock: false,
    images: [
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/made68pro/MelGeek_MADE68_Pro_12.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/made68pro/MelGeek_MADE68_Pro_1.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/made68pro/MelGeek_MADE68_Pro_10.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/made68pro/MelGeek_MADE68_Pro_11.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/made68pro/MelGeek_MADE68_Pro_9.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/made68pro/MelGeek_MADE68_Pro_14.jpg",
    ],
    category: "keyboards",
    specs: {
      layout: "68% (68 keys)",
      case: "ABS + PC with Aluminum Alloy",
      keycaps: "ABS Double-Shot Keycaps",
      switches: "Hot‑swap / magnetic switches",
      pollingRate: "8K Hz",
      latency: "0.125ms",
      singleKeyScanRate: "256K",
      precision: "0.01mm",
      features: [
        "Zero Dead-Zone",
        "Electric Light-Box",
        "Functions SOCD / DKS / RT / MT / TGL / Key remapping",
        "Wired Connection",
        "Proprietary MCR original height profile",
      ],
    },
    options: null,
  },
  {
    id: "storm68",
    title: "NZO STORM68 HE",
    short:
      "NZO STORM68 HE Full Aluminum CNC Shell Hall Effect Keyboard with precision 0.005mm + 256K Scanning Rate",
    price: 75,
    layout: "68",
    available: false,
    isNew: false,
    lowStock: false,
    images: [
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/1.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/22.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/33.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/44.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/55.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/66.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/2.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/3.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/4.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/6.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/7.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/8.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/9.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/11.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/specs.jpg",
    ],
    category: "keyboards",
    specs: {
      layout: "68% (68 keys)",
      case: "Full Aluminum CNC Shell",
      pollingRate: "8K Hz",
      singleKeyScanRate: "256K",
      fullKeyScanRate: "32K",
      precision: "0.005mm",
      latency: "0.08ms",
      rtRange: "0.005 ~ 3.3mm",
      features: [
        "Global Travel 0.005mm",
        "16.7 million ARGB, 500Hz Refresh",
        "Carbon Fiber / Aluminum Position Plate variants",
        "PBT Double / Theme Keycaps",
        "Functions SOCD / DKS / RT / MT / Key remapping",
        "Web-Driver Supported (NZO GEAR HUB)",
      ],
    },
    options: [
      {
        name: "Cyber-Yellow",
        available: true,
        price: 70,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/cyberpunk.png",
      },
      {
        name: "Ethernal Blue",
        available: true,
        price: 75,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/blue.png",
      },
      {
        name: "Sharp Silver",
        available: false,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/storm68/black.png",
      },
    ],
  },
  {
    id: "ace68turbo",
    title: "MCHOSE ACE68 TURBO",
    short:
      "MCHOSE Ace 68 Turbo – World's First 16K Polling Rate HE Aluminum Keyboard",
    price: 140,
    layout: "68",
    available: false,
    isNew: false,
    lowStock: false,
    sellerRating: 9,
    images: [
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/ace68turbo/Dynamic_RGB_Lightbox_with_Music_Sync_on_Ace_68_Turbo.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/ace68turbo/Multi-Function_Control_Knob_and_RT_Button_on_Ace_68_Turbo.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/ace68turbo/31.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/ace68turbo/22.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/ace68turbo/Ace_68_Turbo_65_Hot-Swappable_Rapid_Trigger_Keyboard_1.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/ace68turbo/Ace_68_Turbo_Keyboard_Structure_Layers_Aluminum_Plate_Foam_PCB2.png",
    ],
    category: "keyboards",
    specs: {
      layout: "65% (68 keys)",
      case: "Full Aluminum CNC",
      switches: "Hot‑swap / magnetic switches",
      pollingRate: "16K/8K Hz",
      latency: "0.06ms / 0.125ms",
      singleKeyScanRate: "256K",
      features: [
        "Zero Dead-Zone",
        "2/4 PCB Layers",
        "Adaptive Dynamic Calibration 2.0",
        "Electric Light-Box",
        "3 Rapid-Trigger profile support",
        "RT Button profile switch",
        "Multi-Function Knob",
        "Dual Drivers Support",
        "16M ARGB, Music Rhythm 2.0, Aura Sync",
        "Wired Connection",
        "Proprietary MCR height profile",
      ],
    },
    options: null,
  },
  {
    id: "iqunix-ez63",
    title: "IQUNIX EZ63 8K Magnetic HE",
    short: "IQUNIX EZ63 8KHz Polling Rate Magnetic Switch Gaming Keyboard",
    price: 150,
    layout: "60",
    available: false,
    isNew: false,
    lowStock: false,
    images: [
      "https://cdn.shopify.com/s/files/1/0676/7853/5986/files/ml001.de632f1c_4207f70c-d610-4e2e-b699-1d100cc38f3e.jpg?v=1718718976",
      "https://cdn.shopify.com/s/files/1/0676/7853/5986/files/l004.a6559626_1cbfda67-2cb8-4eea-9c44-21b2c20fbc77.jpg?v=1718718976",
      "https://m.media-amazon.com/images/I/71oXr1eldGL.jpg",
      "https://iqunix.com/cdn/shop/articles/0347.jpg?v=1724826927",
      "https://m.media-amazon.com/images/I/61KjyMs2WxL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71ttPO02TfL._AC_SL1500_.jpg",
    ],
    category: "keyboards",
    specs: {
      layout: "60% (64 keys)",
      pollingRate: "8000Hz",
      latency: "0.125ms",
      singleKeyScanRate: "16,000Hz",
      fullKeyScanRate: "2,000Hz - 4,000Hz (Dynamic)",
      precision: "RT Sensitivity 0.05mm",
      features: [
        "Adjustable Actuation 0.1mm - 4.0mm",
        "Gateron Star Trail / Jade Pro Magnetic Switches",
        "Full CNC Aluminum Chassis",
        "Esports Gasket Mount Structure",
        "Web-based Driver",
        "Double-shot PBT Keycaps",
        "Dimensions: 307 x 124.5 x 22mm | Weight: ~1.0kg",
      ],
    },
    options: [
      {
        name: "Black / Star Trail Switches",
        available: true,
        image: "https://m.media-amazon.com/images/I/5191XtHTByL.jpg",
      },
      {
        name: "White / Magnetic Jade Pro",
        available: true,
        image:
          "https://iqunix.com/cdn/shop/files/20250310-095053.jpg?v=1742280303&width=1946",
      },
      {
        name: "Pink / Pink Jade Pro",
        available: true,
        image:
          "https://cdn.mwave.com.au/images/400/iqunix_ez63_pink_rgb_he_mechanical_gaming_keyboard_star_trail_switch_ac81339_62101.jpg",
      },
    ],
  },
  {
    id: "aula-ag60-series",
    title: "AULA AG60 HE Series",
    short: "AULA AG60 Dual-Engine 8K Magnetic Switch Aluminum Keyboard",
    price: 135,
    layout: "60",
    available: false,
    isNew: false,
    lowStock: false,
    images: [
      "https://www.aulastar.com/uploads/allimg/20250826/1-250R61HU1644.jpg",
      "https://www.aulastar.com/uploads/allimg/20250826/1-250R61HU1R2.jpg",
      "https://www.aulastar.com/uploads/allimg/20250826/1-250R61HU2628.jpg",
      "https://www.aulastar.com/uploads/allimg/20250826/1-250R61HU4939.jpg",
      "https://www.aulastar.com/uploads/allimg/20250826/1-250R61HUD64.jpg",
      "https://www.aulastar.com/uploads/allimg/20250826/1-250R61HU5S1.jpg",
      "https://www.aulastar.com/uploads/allimg/20250826/1-250R61HUL44.jpg",
      "https://www.aulastar.com/uploads/allimg/20250826/1-250R61HUSQ.jpg",
      "https://www.aulastar.com/uploads/allimg/20250826/1-250R61HUR53.jpg",
      "https://www.aulastar.com/uploads/allimg/20250826/1-250R61HZ22J.jpg",
    ],
    category: "keyboards",
    specs: {
      layout: "60% (61 keys)",
      pollingRate: "8000Hz",
      latency: "0.1ms",
      singleKeyScanRate: "2304KHz Per-Key",
      fullKeyScanRate: "256K Full Key Matrix",
      precision: "0.001mm RT Precision",
      features: [
        "Adjustable Zero-Dead-Zone",
        "Aether Magnetic Switches",
        "Carbon Fiber Positioning Plate",
        "CNC Anodized Aluminum Case",
        "5-Layer Silent Noise Reduction",
        "Twin-Star Per-key RGB (130 ARGB LEDs)",
        "Functions: SOCD / DKS / RT / MT / TGL / Key Remapping",
      ],
    },
    options: [
      {
        name: "AG60 Max / Warm Silver",
        available: true,
        image:
          "https://www.aulastar.com/uploads/allimg/20250819/1-250Q9152PT54.jpg",
        price: 135,
      },
      {
        name: "AG60 Max / Racing Red",
        available: false,
        image:
          "https://www.aulastar.com/uploads/allimg/20250819/1-250Q9152PKU.jpg",
        price: 150,
      },
    ],
  },
  {
    id: "cidoo-qk61-v2",
    title: "CIDOO QK61 V2",
    short: "CIDOO QK61 V2 Tri-Mode VIA Programmable Gasket Mechanical Keyboard",
    price: 40,
    layout: "60",
    available: false,
    isNew: false,
    lowStock: false,
    images: [
      "https://cdn.shopify.com/s/files/1/0691/8337/3602/files/203A3777.jpg?v=1728442680",
      "https://cdn.shopify.com/s/files/1/0691/8337/3602/files/203A3739.jpg?v=1728442680",
      "https://cdn.shopify.com/s/files/1/0691/8337/3602/files/203A3789.jpg?v=1728442680",
      "https://cdn.shopify.com/s/files/1/0691/8337/3602/files/203A3807.jpg?v=1728442680",
      "https://cdn.shopify.com/s/files/1/0691/8337/3602/files/203A3801.jpg?v=1728442680",
      "https://cdn.shopify.com/s/files/1/0691/8337/3602/files/203A3755.jpg?v=1728442680",
      "https://cdn.shopify.com/s/files/1/0691/8337/3602/files/203A3760.jpg?v=1728442680",
    ],
    category: "keyboards",
    specs: {
      layout: "60% (61 keys)",
      features: [
        "Tri-Mode: 2.4G / Bluetooth 5.0 / Wired USB-C",
        "Wired Polling Rate: 1000Hz (3ms Latency)",
        "Polling Rate: 1000Hz",
        "VIA Programmable (QMK)",
        "Hot-swappable PCB (3/5-pin)",
        "CIDOO Pearl White Linear Switches (Pre-lubed)",
        "Pre-lubed Plate-mount stabilizers",
        "Gasket Mount with Polycarbonate Plate",
        "3000mAh Battery",
        "5-Layer Sound Dampening Foam",
        "Double-shot PBT + Transparent PC Keycaps",
        "South-facing RGB LEDs",
      ],
    },
    options: [
      {
        name: "White Case",
        available: true,
        image:
          "https://cdn.shopify.com/s/files/1/0691/8337/3602/files/203A3739.jpg?v=1728442680",
      },
      {
        name: "Black Case",
        available: false,
        image:
          "https://cdn.shopify.com/s/files/1/0691/8337/3602/files/203A3777.jpg?v=1728442680",
      },
    ],
  },
  {
    id: "atkrs7",
    title: "ATK RS-7",
    short:
      "ATK RS7 eSports Hall Effect Keyboard, Premium looking 75% keyboard with CNC Top-Case and Aluminum Position Plate",
    price: 70,
    layout: "75",
    available: false,
    isNew: false,
    lowStock: false,
    images: [
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/atkrs7v1/thumbnail.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/atkrs7v1/1.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/atkrs7v1/2.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/atkrs7v1/3.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/atkrs7v1/4.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/atkrs7v1/5.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/atkrs7v1/6.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/atkrs7v1/7.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/atkrs7v1/8.png",
    ],
    category: "keyboards",
    specs: {
      layout: "75% (81 keys)",
      case: "CNC Top Case",
      keycaps: "5-Sided Dye-Sub Keycaps",
      pollingRate: "8K Hz",
      latency: "0.3ms",
      precision: "0.05mm - 0.02mm",
      rtRange: "0.1 ~ 3.4mm",
      features: [
        "Resilient GAS Structure",
        "4 Padding Layers",
        "ATK V1 Stabilizer",
        "Functions SOCD / DKS / RT / MT / TGL / Key Remapping",
        "Mahjong-inspired HIFI Sound",
      ],
    },
    options: [
      {
        name: "Rainbow IP, No-Backlit",
        available: true,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/atkrs7v1/no_rgb.png",
      },
      {
        name: "Rainbow IP (RGB)",
        available: false,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/atkrs7v1/rgb.png",
      },
    ],
  },
];
