export const mice = [
    {
      id: "scyroxv8",
      title: "Scyrox V8",
      short:
        "36-Gram Ultra-Lightweight Wireless Gaming Mouse with 8K Polling Rate",
      price: 60,
      layout: "36g",
      available: false,
      isNew: false,
      lowStock: false,
      images: [
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/scyroxv8/10.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/scyroxv8/20.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/scyroxv8/30.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/scyroxv8/40.jpg",
      ],
      specs: [
        "Paw3950 Sensor",
        "36Gram Weight",
        "8K Hz Polling-Rate",
        "MCU Nordic-52840",
        "Track Speed 750IPS",
        "30k DPI",
        "Acceleration 50g",
        "Omron Optical Switches",
        "Wireless / Wired",
        "Web-Based Driver",
        "Yellow Color Available",
      ],
      options: null,
    },
    {
      id: "atkf1pro",
      title: "ATK Blazing Sky F1 Pro",
      short:
        "45-Gram Wireless Gaming Mouse with 8K Polling Rate, PAW3950 Sensor",
      price: 80,
      layout: "45g",
      available: false,
      isNew: false,
      lowStock: false,
      images: [
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/blazingF1pro/2.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/blazingF1pro/1.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/blazingF1pro/3.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/blazingF1pro/4.png",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/blazingF1pro/5.png",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/blazingF1pro/6.png",
      ],
      specs: [
        "PAW3950 Optical Sensor",
        "45g ± 2g Ultralight Weight",
        "8K Hz Wireless/Wired Polling Rate",
        "Nordic 52840 MCU",
        "Track Speed 750 IPS",
        "Max DPI 36000",
        "Acceleration 70G",
        "Omron Optical Switches",
        "Wireless (2.4GHz) / Wired / Bluetooth (varies by model)",
        "Ice-feeling Coating",
        "ATK HUB/Web Driver Supported",
      ],
      options: null,
    },
    {
      id: "vxer1se",
      title: "VXE R1 SE (Dragonfly R1 SE)",
      short: "51-Gram Lightweight Tri-Mode Wireless Gaming Mouse",
      price: 35,
      layout: "51g",
      available: false,
      isNew: false,
      lowStock: false,
      images: [
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/1.png",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/2.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/3.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/4.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/5.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/6.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/7.jpg",
      ],
      specs: [
        "PAW3395 SE Sensor",
        "51g Weight (R1 SE/R1)",
        "Up to 2K Hz Polling Rate (1K Hz standard, 2K on some models)",
        "Nordic/BEKEN Chipset",
        "Track Speed 400 IPS",
        "Max DPI 18000",
        "Acceleration 40G",
        "Huano/IceBerry Switches (Varies)",
        "Tri-Mode: 2.4G Wireless / Bluetooth 5.3 / Wired Type-C",
        "520mAh Battery (R1 SE+ model), 250mAh (R1 SE)",
        "Web-Driver Customization",
      ],
      options: null,
    },
    {
      id: "lamzumayax",
      title: "Lamzu Maya X 8K Wireless",
      short: "47-Gram Symmetrical Gaming Mouse with 8K Polling Rate",
      price: 120, // Approximate price
      layout: "47g",
      available: false,
      isNew: false,
      lowStock: true,
      images: [
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/1.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/2.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/3.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/4.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/5.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/6.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/7.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/8.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/9.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/10.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/11.jpg",
        "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/12.jpg",
      ],
      specs: [
        "PixArt 3950 Sensor",
        "47g Weight",
        "8K Hz Polling Rate (8K Dongle Included)",
        "Nordic 52840 MCU",
        "Track Speed 750 IPS",
        "Max DPI 30000",
        "Acceleration 50G",
        "Omron Optical Switches",
        "Symmetrical Shape (Small/Medium Hands)",
        "Wireless (2.4GHz) / Wired (Type-C)",
        "Web-Based Aurora Driver",
      ],
      options: [
        {
          name: "Purple Shadow",
          available: false,
          image:
            "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/purple.jpg",
        },
        {
          name: "Light Pink",
          available: false,
          image:
            "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/pink.jpg",
        },
        {
          name: "Charcoal Black",
          available: false,
          image:
            "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/black.jpg",
        },
        {
          name: "White",
          available: false,
          image:
            "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/white.jpg",
        },
        {
          name: "Cloud Gray",
          available: false,
          image:
            "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/cloud.jpg",
        },
      ],
    },
  ];