export const mice = [
  {
    id: "VGNDragonFlyF2SE",
    title: "VGN Dragonfly F2 Series",
    short: "Lightweight Wireless Gaming Dual 8K Reporting Rate Mouse",
    price: 40,
    layout: "50g",
    available: false,
    isNew: false,
    lowStock: false,
    sellerRating: 8.5,
    images: [
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/2.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/1.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/3.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/4.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/5.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/7.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/8.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/9.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/10.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/11.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/12.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/13.jpg",
    ],
    category: "mice",
    specs: {
      latency: "0.4ms / 0.175ms",
      battery: "500-800mAh (Version Dependent)",
      coating: "Fine Skin-Like Coating",
      sensor: "PAW3395 / PAW3950 / PAW3395 Extreme",
      weight: "55g ± 2g",
      pollingRate: "8K Hz",
      mcu: "Jiangmeng CX52860 / Nordic 52840 / Nordic 54L15",
      dpi: "50 - 42000 (Version Dependent)",
      switches:
        "Honor Mechanical Micro Swicth / Omron Micro Optical Switch / Custom Kaihua Switch",
      connectivity: "Wireless (2.4GHz) / Wired",
      features: [
        "Custom VHub Client / Web Driver Supported",
      ],
    },
    options: [
      {
        name: "Pink- Pro Max",
        available: false,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/pink.jpg",
        price: 40,
      },
      {
        name: "Green - Pro Max",
        available: false,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/green.jpg",
        price: 40,
      },
      {
        name: "Black - Pro Max",
        available: false,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/black.jpg",
        price: 40,
      },
      {
        name: "White - Pro Max",
        available: false,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vgndragonflyF2/white.jpg",
        price: 40,
      },
    ],
  },
  {
    id: "atkf1pro",
    title: "ATK Blazing Sky F1 SE",
    short: "45-Gram Wireless Gaming Mouse with 8K Polling Rate, PAW3950 Sensor",
    price: 70,
    layout: "45g",
    available: false,
    isNew: false,
    lowStock: false,
    sellerRating: 9.5,
    images: [
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/blazingF1pro/2.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/blazingF1pro/1.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/blazingF1pro/3.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/blazingF1pro/4.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/blazingF1pro/5.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/blazingF1pro/6.png",
      "https://www.atk.store/cdn/shop/files/F1-2_07fcd364-5e20-42b6-be3d-098271023e54.jpg?v=1745389030",
      "https://www.atk.store/cdn/shop/files/F1-1_18fb359b-c4f9-4f68-908c-eae9df01c251.jpg?v=1745389030",
      "https://www.atk.store/cdn/shop/files/F1-5_b2dc4f16-32d5-4012-bcc2-7d319a83d1f0.jpg?v=1745389229",
    ],
    category: "mice",
    specs: {
      latency: "0.4ms",
      battery: "200-800mAh (Version Dependent)",
      coating: "Ice-feeling Coating",
      sensor: "PAW3950 / PAW3950 ULTRA",
      weight: "45g ± 2g",
      pollingRate: "8K Hz",
      mcu: "Nordic 52840",
      trackingSpeed: "750 IPS",
      dpi: "36000",
      acceleration: "70G",
      switches: "Omron Optical Switches",
      connectivity: "Wireless (2.4GHz) / Wired / Bluetooth",
      features: ["ATK HUB/Web Driver Supported"],
    },
    options: [
      {
        name: "Blazing Sky F1 Pro - Black",
        available: false,
        image: "https://www.atk.store/cdn/shop/files/ATK_Blazing_Sky_F1_Extreme_Black.jpg?v=1756979076"
      },
      {
        name: "Blazing Sky F1 Pro - White",
        available: false,
        image: "https://www.atk.store/cdn/shop/files/ATK_Blazing_Sky_F1_Extreme_White.jpg?v=1756979076"
      }
    ]
  },
  {
    id: "vxer1se",
    title: "VXE R1 SE (Dragonfly R1 SE)",
    short: "51-Gram Lightweight Tri-Mode Wireless Gaming Mouse",
    price: 35,
    layout: "51g",
    available: false,
    isNew: false,
    lowStock: false,
    sellerRating: 7,
    images: [
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/1.png",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/2.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/3.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/4.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/5.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/6.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/vxer1se/7.jpg",
    ],
    category: "mice",
    specs: {
      battery: "500mAh / 250mAh (Version Dependent)",
      sensor: "PAW3395 SE",
      weight: "51g",
      pollingRate: "Up to 2K Hz",
      chipset: "Nordic/BEKEN",
      trackingSpeed: "400 IPS",
      dpi: "18000",
      acceleration: "40G",
      switches: "Huano/IceBerry (varies)",
      connectivity: "Tri-Mode: 2.4G / Bluetooth 5.3 / Wired Type-C",
      battery: "520mAh / 250mAh (model dependent)",
      features: ["Web-Driver Customization"],
    },
    options: null,
  },
  {
    id: "lamzumayax",
    title: "Lamzu Maya X 8K Wireless",
    short: "47-Gram Symmetrical Gaming Mouse with 8K Polling Rate",
    price: 120,
    layout: "47g",
    available: false,
    isNew: false,
    lowStock: true,
    sellerRating: 9.5,
    images: [
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/1.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/2.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/3.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/4.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/5.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/6.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/7.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/8.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/9.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/10.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/11.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/12.jpg",
    ],
    category: "mice",
    specs: {
      latency: "0.5ms / -0.8ms (8K Hz Polling Rate)",
      battery: "300mAh",
      coating: "Matte Dry Grip Coating",
      sensor: "PixArt 3950",
      weight: "47g",
      pollingRate: "8K Hz",
      mcu: "Nordic 52840",
      trackingSpeed: "750 IPS",
      dpi: "30000",
      acceleration: "50G",
      switches: "Omron Optical Switches",
      connectivity: "Wireless (2.4GHz) / Wired (Type-C)",
      features: ["Symmetrical Shape (Small/Medium)", "Web-Based Aurora Driver"],
    },
    options: [
      {
        name: "Purple Shadow",
        available: false,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/purple.jpg",
      },
      {
        name: "Light Pink",
        available: false,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/pink.jpg",
      },
      {
        name: "Charcoal Black",
        available: false,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/black.jpg",
      },
      {
        name: "White",
        available: false,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/white.jpg",
      },
      {
        name: "Cloud Gray",
        available: false,
        image:
          "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/mayaX/cloud.jpg",
      },
    ],
  },
  {
    id: "scyroxv8",
    title: "Scyrox V8",
    short:
      "36-Gram Ultra-Lightweight Wireless Gaming Mouse with 8K Polling Rate",
    price: 60,
    layout: "36g",
    available: false,
    isNew: false,
    lowStock: false,
    images: [
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/scyroxv8/10.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/scyroxv8/20.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/scyroxv8/30.jpg",
      "https://raw.githubusercontent.com/Glsswrks/hekeebcambodia/main/images/scyroxv8/40.jpg",
    ],
    category: "mice",
    sellerRating: 8.0,
    specs: {
      battery: "250mAh",
      coating: "Matte Dry Coating",
      latency: "1.3ms - 0.4ms",
      sensor: "PAW3950",
      weight: "36g",
      pollingRate: "8K Hz",
      mcu: "Nordic 52840",
      trackingSpeed: "750 IPS",
      dpi: "30000",
      acceleration: "50g",
      switches: "Omron Optical Switches",
      connectivity: "Wireless / Wired",
      features: ["Web-Based Driver", "Yellow Color Available"],
    },
    options: null,
  },
];
