export const mousepads = [
  {
    id: "pulsar-yui-edition",
    title: "Pulsar Yui Edition Glass Mousepad (Replica)",
    short: "490x430mm Tempered Glass Mousepad - XXL Size (Aimerz Yui Edition)",
    price: 65,
    layout: "490x430",
    no_info: true,
    available: false,
    isNew: false,
    lowStock: false,
    images: [
      "https://www.pulsar.gg/cdn/shop/files/Pulsar-Superglide-Glass-mousepad_XXL_Aimerz_Yui_main.jpg?v=1752193016",
    ],
    category: "mousepads",
    specs: [
      "Tempered Glass Surface",
      "Size: 490x430mm",
      "Coating + Full Coverage Primer",
    ],
    options: null,
  },
  {
    id: "pulsar-ayane-edition",
    title: "Pulsar Ayane Edition Glass Mousepad (Replica)",
    short: "490x430mm Tempered Glass Mousepad - XXL Size (Ayane Edition)",
    price: 50,
    layout: "490x430",
    no_info: true,
    available: false,
    isNew: false,
    lowStock: false,
    images: [
      "https://www.pulsar.gg/cdn/shop/files/Pulsar_Superglide_Glass_mousepad_XXL_Aimerz_Ayane_main.jpg?v=1712547879",
    ],
    category: "mousepads",
    specs: [
      "Tempered Glass Surface",
      "Size: 490x430mm",
      "Full Coverage Primer",
    ],
    options: null,
  },
  {
    id: "pulsar-aimerz-edition",
    title: "Pulsar Aimerz Edition Glass Mousepad (Replica)",
    short: "490x430mm Tempered Glass Mousepad - XXL Size (Aimerz Edition)",
    price: 50,
    layout: "490x430",
    no_info: true,
    available: false,
    isNew: false,
    lowStock: false,
    images: [
      "https://www.pulsar.gg/cdn/shop/files/Pulsar_Superglide_Glass_mousepad_XXL_Aimerz_main.jpg?v=1701254311",
    ],
    category: "mousepads",
    specs: [
      "Tempered Glass Surface",
      "Size: 490x430mm",
      "Full Coverage Primer",
    ],
    options: null,
  },
  {
    id: "pulsar-koharu-edition",
    title: "Pulsar Koharu Edition Glass Mousepad (Replica)",
    short: "490x430mm Tempered Glass Mousepad - XXL Size (Koharu Edition)",
    price: 50,
    layout: "490x430",
    no_info: true,
    available: false,
    isNew: false,
    lowStock: false,
    images: [
      "https://www.pulsar.gg/cdn/shop/files/Pulsar_Superglide_Glass_mousepad_XXL_Aimerz_Koharu_main.jpg?v=1729639565",
    ],
    category: "mousepads",
    specs: [
      "Tempered Glass Surface",
      "Size: 490x430mm",
      "Full Coverage Primer",
    ],
    options: null,
  },
];
